### PR TITLE
TART_EXECUTOR_INSTALL_GITLAB_RUNNER: deprecate "true"

### PR DESCRIPTION
**Pull request by edigaryev**
In favor of explicit "brew" and "curl" installation methods.

Tested all combinations manually on `ghcr.io/cirruslabs/macos-sonoma-base:latest`.

Resolves https://github.com/cirruslabs/gitlab-tart-executor/issues/48.

### CODE REVIEW

**Comment by fkorotkov** [comment]
What do you think of `host` option in the future? https://github.com/cirruslabs/gitlab-tart-executor/issues/48#issuecomment-1888642685

**Comment by edigaryev** [comment]
> What do you think of `host` option in the future? [#48 (comment)](https://github.com/cirruslabs/gitlab-tart-executor/issues/48#issuecomment-1888642685)

From the linked issue:

> for the specific versions, tart would pick an appropriate installation method (though for simplicity's sake, i would just go for `curl`)

I think we should only implement `host` if separate `brew` and `curl` wouldn't cut it.

**Review by fkorotkov — APPROVED** [review]
Your call. Anyone interested in the 'host' strategy please create a separate issue.

**Comment by umlaeute** [comment]
how does this solve #48 ? the title of my issue was "force a given version of gitlab-runner?" which i do not see addressed at all.

**Pull request merged**
